# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto import fedmed_pb2 as fedmed__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fedmed_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FedMedServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/fedmed.FedMedService/HealthCheck',
                request_serializer=fedmed__pb2.HealthRequest.SerializeToString,
                response_deserializer=fedmed__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.RegisterHospital = channel.unary_unary(
                '/fedmed.FedMedService/RegisterHospital',
                request_serializer=fedmed__pb2.RegisterHospitalRequest.SerializeToString,
                response_deserializer=fedmed__pb2.RegisterHospitalResponse.FromString,
                _registered_method=True)
        self.GetHospitalStatus = channel.unary_unary(
                '/fedmed.FedMedService/GetHospitalStatus',
                request_serializer=fedmed__pb2.GetHospitalStatusRequest.SerializeToString,
                response_deserializer=fedmed__pb2.GetHospitalStatusResponse.FromString,
                _registered_method=True)
        self.GetAllHospitals = channel.unary_unary(
                '/fedmed.FedMedService/GetAllHospitals',
                request_serializer=fedmed__pb2.GetAllHospitalsRequest.SerializeToString,
                response_deserializer=fedmed__pb2.GetAllHospitalsResponse.FromString,
                _registered_method=True)


class FedMedServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterHospital(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHospitalStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllHospitals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FedMedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=fedmed__pb2.HealthRequest.FromString,
                    response_serializer=fedmed__pb2.HealthResponse.SerializeToString,
            ),
            'RegisterHospital': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterHospital,
                    request_deserializer=fedmed__pb2.RegisterHospitalRequest.FromString,
                    response_serializer=fedmed__pb2.RegisterHospitalResponse.SerializeToString,
            ),
            'GetHospitalStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHospitalStatus,
                    request_deserializer=fedmed__pb2.GetHospitalStatusRequest.FromString,
                    response_serializer=fedmed__pb2.GetHospitalStatusResponse.SerializeToString,
            ),
            'GetAllHospitals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllHospitals,
                    request_deserializer=fedmed__pb2.GetAllHospitalsRequest.FromString,
                    response_serializer=fedmed__pb2.GetAllHospitalsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fedmed.FedMedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fedmed.FedMedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FedMedService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedmed.FedMedService/HealthCheck',
            fedmed__pb2.HealthRequest.SerializeToString,
            fedmed__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterHospital(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedmed.FedMedService/RegisterHospital',
            fedmed__pb2.RegisterHospitalRequest.SerializeToString,
            fedmed__pb2.RegisterHospitalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHospitalStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedmed.FedMedService/GetHospitalStatus',
            fedmed__pb2.GetHospitalStatusRequest.SerializeToString,
            fedmed__pb2.GetHospitalStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllHospitals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedmed.FedMedService/GetAllHospitals',
            fedmed__pb2.GetAllHospitalsRequest.SerializeToString,
            fedmed__pb2.GetAllHospitalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
