# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fedmed.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'fedmed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66\x65\x64med.proto\x12\x06\x66\x65\x64med\"$\n\rHealthRequest\x12\x13\n\x0bhospital_id\x18\x01 \x01(\t\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"W\n\x17RegisterHospitalRequest\x12\x13\n\x0bhospital_id\x18\x01 \x01(\t\x12\x15\n\rhospital_name\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\"<\n\x18RegisterHospitalResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\x18GetHospitalStatusRequest\x12\x13\n\x0bhospital_id\x18\x01 \x01(\t\"\x8b\x01\n\x19GetHospitalStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhospital_id\x18\x02 \x01(\t\x12\x15\n\rhospital_name\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x0f\n\x07message\x18\x06 \x01(\t\"\x18\n\x16GetAllHospitalsRequest\"X\n\x08Hospital\x12\x13\n\x0bhospital_id\x18\x01 \x01(\t\x12\x15\n\rhospital_name\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"`\n\x17GetAllHospitalsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12#\n\thospitals\x18\x02 \x03(\x0b\x32\x10.fedmed.Hospital\x12\x0f\n\x07message\x18\x03 \x01(\t2\xd2\x02\n\rFedMedService\x12<\n\x0bHealthCheck\x12\x15.fedmed.HealthRequest\x1a\x16.fedmed.HealthResponse\x12U\n\x10RegisterHospital\x12\x1f.fedmed.RegisterHospitalRequest\x1a .fedmed.RegisterHospitalResponse\x12X\n\x11GetHospitalStatus\x12 .fedmed.GetHospitalStatusRequest\x1a!.fedmed.GetHospitalStatusResponse\x12R\n\x0fGetAllHospitals\x12\x1e.fedmed.GetAllHospitalsRequest\x1a\x1f.fedmed.GetAllHospitalsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fedmed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=24
  _globals['_HEALTHREQUEST']._serialized_end=60
  _globals['_HEALTHRESPONSE']._serialized_start=62
  _globals['_HEALTHRESPONSE']._serialized_end=111
  _globals['_REGISTERHOSPITALREQUEST']._serialized_start=113
  _globals['_REGISTERHOSPITALREQUEST']._serialized_end=200
  _globals['_REGISTERHOSPITALRESPONSE']._serialized_start=202
  _globals['_REGISTERHOSPITALRESPONSE']._serialized_end=262
  _globals['_GETHOSPITALSTATUSREQUEST']._serialized_start=264
  _globals['_GETHOSPITALSTATUSREQUEST']._serialized_end=311
  _globals['_GETHOSPITALSTATUSRESPONSE']._serialized_start=314
  _globals['_GETHOSPITALSTATUSRESPONSE']._serialized_end=453
  _globals['_GETALLHOSPITALSREQUEST']._serialized_start=455
  _globals['_GETALLHOSPITALSREQUEST']._serialized_end=479
  _globals['_HOSPITAL']._serialized_start=481
  _globals['_HOSPITAL']._serialized_end=569
  _globals['_GETALLHOSPITALSRESPONSE']._serialized_start=571
  _globals['_GETALLHOSPITALSRESPONSE']._serialized_end=667
  _globals['_FEDMEDSERVICE']._serialized_start=670
  _globals['_FEDMEDSERVICE']._serialized_end=1008
# @@protoc_insertion_point(module_scope)
